services:
  # سرویس پروژه Vue ما
  app:
    # بیلد کردن ایمج از Dockerfile موجود در همین پوشه
    build: .
    # نام کانتینر برای راحتی در کار
    container_name: vue-tailwind-app
    # map کردن پورت‌ها: پورت سیستم شما : پورت داخل کانتینر
    ports:
      - "5173:5173"
    # بخش مهم برای همگام‌سازی کد و Live-Reload
    volumes:
      # همگام‌سازی پوشه فعلی سیستم با پوشه /app داخل کانتینر
      - .:/app
      # این خط باعث میشه پوشه node_modules داخل کانتینر با پوشه سیستم جایگزین نشه
      # و وابستگی‌های نصب شده داخل کانتینر باقی بمونن
      - /app/node_modules